blank_issues_enabled: false

contact_links:
  - name: Soporte / Support – Modulum Studio
    url: mailto:support@modulumstudio.com
    about: Contact us directly for anything unrelated to bugs or feature requests.
